# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.

# require "environment"
# require "mongoid"

# RSpec.configure do |config|
#   # config.include FactoryGirl::Syntax::Methods

#   config.before(:suite) do
#     # begin
#     #   DatabaseCleaner.start
#     # ensure
#     #   DatabaseCleaner.clean
#     # end

#   end

#   Mongoid.configure do |config|
#     config.load_configuration(CONFIG)
#   end

#   mongoid_db_name = "mongoid_test_db"
#   CONFIG = {
#     clients: {
#       default: {
#         database: mongoid_db_name,
#         hosts: [ "localhost:27017" ],
#         options: {
#           server_selection_timeout: 0.5,
#           max_pool_size: 1,
#           heartbeat_frequency: 180,
#         }
#       }
#     }
#   }

#   config.expect_with :rspec do |expectations|
#     expectations.include_chain_clauses_in_custom_matcher_descriptions = true
#   end


# end


$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'rubygems'
require 'rspec'
require 'mongoid'

['support/helpers/*.rb'].each do |path|
  Dir["#{File.dirname(__FILE__)}/#{path}"].each do |file|
    require file
  end
end

RSpec.configure(&:raise_errors_for_deprecations!)

Mongoid.configure do |config|
  config.connect_to('mongoid_dynamic_model_test')
end
